### ISSUE TITLE
Formar el equipo completo (10 integrantes)

### ISSUE THREAD

**Issue by JavierCarranza0101** [JavierCarranza0101/Practico-Scrum-ISPC#2]
Encontrar todos los integrantes que faltan para completar el equipo

**Comment by FrancoChalar** [comment]
Ya somos 6. Faltan 2 integrantes de aceptar la invitación como colaboradores.  Hoy coloque en el grupo de WhatsApp para ver quien esta sin grupo

**Comment by JavierCarranza0101** [comment]
Recién escribí en el foro del modelo Programador, para saber la fecha limite de entrega y para ver si hay alguien sin grupo
