### ISSUE TITLE
Resumen Colaborativo "Ceremonias"

### ISSUE THREAD

**Issue by PabloGimenez1813** [JavierCarranza0101/Practico-Scrum-ISPC#4]
En este Issue, debemos insertar colaborativamente material acerca de las Ceremonias de un Scrum

**Comment by FrancoChalar** [comment]
Ceremonias que se realizan a lo largo del proyecto:
Sprint Planning Meeting (reunión de planificación del sprint) : Se produce al iniciar cada Sprint y tiene por objetivo decidir que se va a realizar en el Sprint.

Daily Scrum Meeting (reunión periódica) : Se produce diariamente, y tiene un máximo de 20 min. de duracion Tiene por objeto tratar qué es lo que se hizo, qué se va a hacer y qué problemas se han encontrado, esto a fines de encontrar soluciones en la diaria.

Sprint Review Meeting (reunión de revisión del Sprint) : Se produce al finalizar el Sprint y tiene por mostrar objeto qué es lo que se ha completado y qué no. Debe estar presente el Product Owner.

Sprint Retrospective Meeting (reunión de retrospectiva del Sprint) : Se produce también al finalizar el Sprint y tiene por objeto documentar qué ha funcionado y qué no ha funcionado en el Sprint. La idea de dicha reunión es centrar al equipo en lo que salió bien y en lo que debe mejorar para la próxima iteración. De ninguna manera se centra en lo que salió mal.

**Comment by PabloGimenez1813** [comment]
excelente

**Comment by nicoercu** [comment]
Un Sprint normal tendría los siguiente eventos o ceremonias:

El Sprint Planning al comienzo del Sprint
Daily Scrums a diario
Un Sprint Review al final del Sprint para inspeccionar el incremento realizado.
Y, finalmente, una Retrospectiva para inspeccionar el equipo y levantar mejoras que se apliquen en el siguiente Sprint.
Adicionalmente se ha incorporado también una reunión de Grooming o Refinement, que sirve para, dentro del Sprint, afinar y aclarar ciertas historias de usuario que pudieron quedar pendientes durante el Sprint Planning.

**Comment by IvanaCancinos** [comment]
**Ceremonias de la Metodología Scrum** 
_¿Qué son las ceremonias Scrum y su propósito?_
Las ceremonias de la metodología Scrum son elementos importantes del proceso de desarrollo de software de Agile. No son reuniones sólo por el hecho de reunirse. Más bien, estas ceremonias de Scrum proporcionan el marco para que los equipos realicen el trabajo de manera estructurada, ayuden a establecer expectativas, capaciten al equipo para colaborar de manera efectiva y, en última instancia, alcancen los resultados. Sin embargo, si no se administran de manera adecuada, pueden abrumar el calendario y bajar un poco el valor que deben proporcionar.
A través de la aplicación de estas reuniones de Scrum, cada miembro del equipo de Scrum debe estar capacitado para hacer lo mejor que puede. Cada reunión es de tiempo limitado, intencional y en servicio al equipo general de Scrum. En otras palabras, existen para hacer posible la entrega del software, que es un proyecto bastante complicado.

**Comment by ignacioruizz** [comment]
### ¿Cuál es el objetivo objetivo principal de las Ceremonias en la metodología scrum?

El objetivo de estas ceremonias o eventos es mantener los mínimos necesarios para facilitar que el control empírico de procesos funciona. Scrum define cinco ceremonias principales para cumplir con el control de sus procesos, todas con un sentido de ser propio que hace que sean imprescindibles para esta metodología.

### ¿Cuál es la ceremonia más importante en Scrum?

Probablemente la reunión más importante desde el punto de vista de Agile. Se trata de analizar los avances y cuestionar si el trabajo se está haciendo correctamente. Requiere la participación de todo el equipo, para así lograr mejoras en la forma de gestionar el trabajo.

**Comment by Dayananaranjo** [comment]
ARTEFACTOS DE SCRUM 
Los Artefactos según la guía Scrum, están diseñados para maximizar la transparencia de la información, que es necesaria para asegurar que todo el equipo tenga el mismo entendimiento del Artefacto.

Las decisiones para optimizar el valor y controlar el riesgo se hacen con base en estos Artefactos, por lo tanto si no son lo suficientemente transparentes se puede incurrir en decisiones erróneas.

Pero veamos cuales son estos Artefactos:

Product Backlog
Es una lista ordenada, que contiene todo lo que podría ser necesario en el producto y es la única fuente de requisitos para hacer cambios en el producto.

El único responsable del Product Backlog es el Product Owner. Es el encargado de ordenar y añadir ítems.

Por definición, esta lista nunca está completa, sino que es un ente vivo y dinámico, que va cambiando según lo hace el entorno y el propio producto para ser adecuado, competitivo y útil.

Los ítems que aparecen en el Product Backlog tienen los siguientes atributos:

Descripción
Ordenación
Estimación
Valor
A medida que el producto va siendo usado y se recibe feedback, la lista se va haciendo más larga y detallada.

Los elementos o ítems que están ordenados más arriba, normalmente son los más detallados y claros, ya que serán los más próximos a ser desarrollados.

Sprint Backlog
Son los ítems o elementos del Product Backlog seleccionados para ser ejecutados durante el Sprint en curso. Así pues, el Sprint Backlog es un plan para entregar un Incremento de producto “Terminado” al final del Sprint.

A medida que se va trabajando sobre el producto, va apareciendo nuevo trabajo, que el Equipo de Desarrollo va añadiendo al Sprint Backlog.

El Sprint Backlog solo lo puede modificar durante el Sprint, el Equipo de Desarrollo, así como eliminarlo.

Incremento
Es la suma de todos los elementos del Sprint Backlog “Terminados” más los Incrementos de Sprints anteriores.

“Terminado” significa que puede ser utilizado y que además cumple con la “Definición de Terminado”, es decir, lo que todo el mundo entiende dentro del equipo por terminado.

Como siempre, estaré encantado de recibir tus comentarios y si te gustó, comparte por favor.
