### ISSUE TITLE
Resumen colaborativo "Artefactos"

### ISSUE THREAD

**Issue by PabloGimenez1813** [JavierCarranza0101/Practico-Scrum-ISPC#5]
**_Agregar unas palabritas cada uno para sumar a la practica ;-)_**

**Comment by JavierCarranza0101** [comment]
Los Artefactos según la guía Scrum, están diseñados para maximizar la transparencia de la información, que es necesaria para asegurar que todo el equipo tenga el mismo entendimiento del Artefacto. Las decisiones para optimizar el valor y controlar el riesgo se hacen con base en estos Artefactos, por lo tanto si no son lo suficientemente transparentes se puede incurrir en decisiones erróneas. Cuales son estos Artefactos:
Product Backlog
Sprint Backlog
Incremento

**Comment by IvanaCancinos** [comment]
**Artefactos en Scrum**

Scrum cuenta con tres artefactos, las herramientas que sirven para solucionar problemas o comprobar el trabajo realizado: - 
- Product Backlog
- Sprint Backlog
- Incremento.

**Product Backlog**
Es una lista activa de la que se responsabiliza el Product Owner. En ella se incluyen las mejoras o necesidades que se detectan a lo largo del proyecto. Decimos que es una lista activa porque los elementos se pueden eliminar, añadir o cambiar de orden.

**Sprint Backlog**
Es la lista de mejoras que el grupo consensua para cada sprint del Product Backlog. Como este, también es flexible: sus elementos pueden cambiar de orden antes de llegar al final del sprint, pero la lista en sí debería ser la misma que al comienzo de dicho sprint.

**Incremento**
Es el resultado final de un sprint: terminar una nueva versión de tu producto, lanzar el servicio final… Cada uno de ellos se añade a los anteriores, y hay que comprobar que todos funcionan a la perfección.

**Comment by Dayananaranjo** [comment]
Los Artefactos según la guía Scrum, están diseñados para maximizar la transparencia de la información, que es necesaria para asegurar que todo el equipo tenga el mismo entendimiento del Artefacto.

Las decisiones para optimizar el valor y controlar el riesgo se hacen con base en estos Artefactos, por lo tanto si no son lo suficientemente transparentes se puede incurrir en decisiones erróneas.

Pero veamos cuales son estos Artefactos:

Product Backlog
Es una lista ordenada, que contiene todo lo que podría ser necesario en el producto y es la única fuente de requisitos para hacer cambios en el producto.

El único responsable del Product Backlog es el Product Owner. Es el encargado de ordenar y añadir ítems.

Por definición, esta lista nunca está completa, sino que es un ente vivo y dinámico, que va cambiando según lo hace el entorno y el propio producto para ser adecuado, competitivo y útil.

Los ítems que aparecen en el Product Backlog tienen los siguientes atributos:

Descripción
Ordenación
Estimación
Valor
A medida que el producto va siendo usado y se recibe feedback, la lista se va haciendo más larga y detallada.

Los elementos o ítems que están ordenados más arriba, normalmente son los más detallados y claros, ya que serán los más próximos a ser desarrollados.

Sprint Backlog
Son los ítems o elementos del Product Backlog seleccionados para ser ejecutados durante el Sprint en curso. Así pues, el Sprint Backlog es un plan para entregar un Incremento de producto “Terminado” al final del Sprint.

A medida que se va trabajando sobre el producto, va apareciendo nuevo trabajo, que el Equipo de Desarrollo va añadiendo al Sprint Backlog.

El Sprint Backlog solo lo puede modificar durante el Sprint, el Equipo de Desarrollo, así como eliminarlo.

Incremento
Es la suma de todos los elementos del Sprint Backlog “Terminados” más los Incrementos de Sprints anteriores.

“Terminado” significa que puede ser utilizado y que además cumple con la “Definición de Terminado”, es decir, lo que todo el mundo entiende dentro del equipo por terminado.

Como siempre, estaré encantado de recibir tus comentarios y si te gustó, comparte por favor.

**Comment by Emilsepeche** [comment]
Cuando hablamos de **ARTEFACTOS** el marco de trabajo Scrum, nos referimos a aquellos elementos físicos que se producen como resultado de la aplicación de Scrum. Los tres principales artefactos son:
-Product Backlog
-Sprint Backlog
-Incremento.

PRODUCT BACKLOG: 
El Product Backlog o pila de producto en un proyecto que sigue la metodología Scrum consiste en una lista con todos los requerimientos iniciales del producto que se va a desarrollar. Se trata de una lista dinámica, que irá evolucionando a medida que lo hace el producto y el entorno del proyecto.

SPRINT BACKLOG: 
El Sprint Backlog es la suma de el Objetivo del Sprint, los elementos del Product Backlog elegidos para el Sprint, más un plan de acción de cómo crear el Incremento de Producto. Es uno de los 3 artefactos de Scrum y se construye durante el evento del Sprint Planning. Es un plan realizado por y para los Developers.
Las características del Sprint Backlog son las siguientes: 
-Sprint Goal (“por qué”).
-El conjunto de elementos del Product Backlog seleccionados para el Sprint (“qué”).
-Un plan para entregar el Incremento (“cómo”).

INCREMENTO:
El Incremento en Scrum es la suma de todos los elementos del Product Backlog completados durante el Sprint presente y el valor de los incrementos de todos los Sprints anteriores. Por tanto, es un paso más hacia la realización del Product Goal u Objetivo de Producto.
