### ISSUE TITLE
resumen colaborativo "Roles"

### ISSUE THREAD

**Issue by PabloGimenez1813** [JavierCarranza0101/Practico-Scrum-ISPC#6]
Tambien para seguir sumando "Roles"_sumar algun cometario_

**Comment by FrancoChalar** [comment]
Roles de Scrum
Los roles de Scrum te ayudan a entender claramente las funciones que desempeñan los miembros involucrados en un sprint o proyecto. Al ser miembro de un equipo Scrum, tendrá plazos para entregar su trabajo, pero puede (dependiendo del rol Scrum asignado), que tenga que dedicar atención a un mayor número de tareas. Existen 3 roles centrales en el Scrum:

Scrum Master: El Scrum Master debe ser un líder servicial que colabore con el funcionamiento y engranaje de todo el equipo. Es responsable de que todo fluya armoniosamente aun cuando haya momentos de tensión; Por fin, es vital que sea un experto en el manejo de Software Scrum y, a la vez, ha de ser alguien atento, despierto, que identifique los riesgos emergentes y se anticipe a ello.
Product Owner: El Product Owner se encarga de afinar las estrategias para la captación de clientes potenciales y selecciona los stakeholders más ideales para la empresa o que se adaptan mejor a la metodología Scrum. Una vez que el Product Owner tiene en su mano el proyecto o las exigencias del stakeholder (cliente), tiene que decidir desear son las principales tareas a cumplir en el proyecto y cuál es la visión del sprint. Un buen Product Owner debe tener la disponibilidad de tiempo necesaria para aclarar dudas al equipo y asistir a todas las reuniones de retroalimentación y evaluación, cubriendo así su rol de manera eficaz.
Equipo de Desarrollo: El Equipo de Desarrollo puede estar conformado por un grupo de 3 a 9 personas especializadas en funciones de desarrollo. El grupo se une para cumplir una tarea determinada, que es ayudada por el Scrum Master. Cada miembro del equipo tiene una función apoyada, pero aun así todos están enfocados en cumplir con la tarea que fue apoyada al grupo como núcleo.

**Comment by nicoercu** [comment]
Scrum es un framework adaptable, iterativo, rápido, flexible y eficaz que está diseñado para entregar valor al cliente durante todo el desarrollo del proyecto. El objetivo primordial es satisfacer las necesidades del cliente a través de un entorno de transparencia en la comunicación, responsabilidad colectiva y progreso continuo.
 Este framework es muy ágil y completo para el desarrollo de proyectos. En Scrum la palabra producto hace referencia a un producto o servicio o cualquier otro resultado que esté de acuerdo con definición de la visión del proyecto, es decir que puede aplicarse a todo tipo de proyectos, pero no todos los proyectos requieren el uso de Scrum.

-Qué equipos necesitan trabajar con la metodología SCRUM?

Piensa por ejemplo que tu proyecto es la construcción de un conjunto de apartamentos, éste no es un proyecto que vaya a tener altas probabilidades de cambios a los largo de su ejecución, además requiere que desde el comienzo esté todo perfectamente documentado con planos y materiales. No es fácilmente adaptable su desarrollo a etapas y no es necesaria la participación permanente del cliente para lograr el mejor resultado, como ves usar Scrum en este caso no traería ventajas.

Aquí entramos en un tema que genera mucha polémica: ¿qué es ser ágil en cuanto a desarrollo de proyectos se refiere?

Es fácil confundirse por la palabra y pensar que ser ágil es ser rápido y esto es un error que puede ser costoso. Ser ágil en desarrollo de proyectos es optimizar el uso de recursos y buscar la mejor forma de llevar a cabo un proyecto aprovechando la experiencia propia y la de los colaboradores.

Los 4 elementos del manifiesto ágil: SCRUM
El manifiesto ágil está basado en 4 elementos:

Individuos e interacciones sobre procesos y herramientas
Software funcionando sobre documentación extensiva
Colaboración con el cliente sobre negociación contractual
Respuesta ante el cambio sobre seguir un plan
Basados en estos elementos han surgido a través del tiempo diferentes frameworks de desarrollo de proyectos que de una u otra manera siguen estos objetivos, uno de éstos es Scrum.

**Comment by nicoercu** [comment]
En Scrum tenemos dos categorías de roles:

1. Roles centrales
Los roles centrales son aquellos que su participación es indispensable para la realización del proyecto, están comprometidos con el proyecto y son responsables del éxito de cada sprint y del proyecto en general. Estos son:

Product owner
Scrum master
Equipo Scrum
2. Roles no centrales
Los roles no centrales son aquellos cuya participación en el proyecto es importante pero no depende de ellos el éxito o fracaso del proyecto, es importante siempre identificar los individuos de esta categoría y mantenerlos siempre presentes, en cualquier momento su rol puede ser decisivo para el proyecto (por ejemplo si es un sponsor). Estos son:

Stakeholders
Cliente
Usuarios
Patrocinador (sponsor)
Vendedores
Scrum Guidance Body
