### ISSUE TITLE
Ventajas  desventajas de "BitBucket"

### ISSUE THREAD

**Issue by PabloGimenez1813** [JavierCarranza0101/Practico-Scrum-ISPC#7]
algunas son:

**Comment by PabloGimenez1813** [comment]
-La mayor diferencia entre Bitbucket y GitHub es que el primero se utiliza principalmente para los repositorios privados, mientras que el segundo es la opción para los repositorios públicos.

**Comment by IvanaCancinos** [comment]
**¿Qué es Bitbucket?**
Es una herramienta para colaboración de coding y con alojamiento en Git, Bitbucket es una excelente opción para equipos profesionales de gestión de proyectos e ingeniería de software.
Es muy similar a GitHub y refleja la mayoría de sus características con ligeras diferencias. Bitbucket esta mejor orientado a los equipos de desarrollo profesional, ya que proporciona grandes beneficios para ellos, como repositorios privados gratuitos, integración con Jira, revisión de código avanzado  y CI/CD (Integración Continua/Despliegue continuo) integrado. Al mismo tiempo, con el crecimiento del equipo, Bitbucket ofrece condiciones de precios más adecuadas comparadas con GitHub y GitLab. Bitbucket también proporciona una modelo de implementación flexible para equipos.

**Principales ventajas de Bitbucket**
Además de elevar el estándar de alojamiento Git, el servidor bitbucket tiene muchas ventajas:

**Rendimiento escalable**
Una de las principales características de bitbucket windows es el hecho de ser responsivo. Gracias a la conectividad de red disponible, el ancho de banda E/S y la potencia informática.
Todo esto permite que no sea vea afectada su capacidad de rendimiento, incluso con una alta demanda de trabajo del servidor. Esto significa que puedes agregar usuarios simultáneos con facilidad.

**Alta disponibilidad**
La alta disponibilidad es de vital importancia y uno de los grandes diferenciales de Bitbucket porque, si algún elemento del clúster tiene algún problema, los demás podrán atender a todas las solicitudes sin pérdida de eficiencia, garantizando siempre un alto rendimiento.


**Espejo inteligente**
Esta función evita perder los largos períodos de tiempo que lleva fusionar el trabajo de todos los miembros del equipo. La función permite configurar copias alojadas en repositorios remotos, manteniendo la sincronización con la instancia principal y la integridad de la información.


**Autocorrección de archivos**
La duplicación inteligente detecta y recupera varios errores sin interrumpir las operaciones. Mientras tanto, el sistema verifica la consistencia de la función de duplicación cada 3 minutos. Esto garantiza la integridad del sistema.

**Seguridad**
En Bitbucket los códigos y Workflows creados están seguros en la nube y se puede acceder a ellos a través de una lista de permisos de IP y verificación de dos pasos. Es posible restringir el acceso solo a ciertos usuarios y controlar los permisos para las acciones de ramificación y verificación de la combinación.


**Desventajas:**

No es de código abierto, pero admite proyectos de código abierto.

**Comment by Dayananaranjo** [comment]
BITBUCKET:
Bitbucket es una herramienta de alojamiento de código y colaboración basada en Git diseñada para equipos. Las inmejorables integraciones de Bitbucket con Jira y Trello están concebidas para unir a todo el equipo de software con el fin de poner en práctica un proyecto.

**Comment by Emilsepeche** [comment]
Bitbucket, Principales características:
Más de 50 herramientas pueden integrarse a Bitbucket, potenciando considerablemente el flujo de trabajo del equipo y elevando la productividad.
*Permite la integración de Jira y Thello, manteniendo los proyectos organizados.

* Entrega continua incorporada. Cree, pruebe e implemente con CI / CD integrado.

*Tiene un sistema de administración de usuarios: Restrinja y dé acceso a determinados usuarios a los proyectos.

*Repositorios privados ilimitados gratuitos.

*Podrá ver en tiempo real cualquier problema de seguridad en el código. 

*Bitbucket es personalizable.
